config/routes.rb
Rails.application.routes.draw do
  resources :trivia_questions do
    resources :answers, path: 'rounds' , only: [:show] do
      post :check, on: :collection
      delete :destroy, on: :collection
    end
    get :play, on: :collection
  end
  get '/ranking',                    to:'pages#ranking'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :trivia_question, optional: true

  validates :trivia_question, presence: true
  validates :answer_text, presence: true, length: { maximum: 255 } #Not going to check for uniqueness cause two users can submit the same question


  def retrieve_answer
    return self if self.correct?
    Answer.find_by(correct: true, trivia_question_id: self.trivia_question_id)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/trivia_question.rb
class TriviaQuestion < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true, reject_if: :all_blank

  validates :user, presence: true
  validates :question, presence: true, length: { maximum: 255 } #Not going to check for uniqueness cause two users can submit the same question
  validate :validate_correct_answers, :validate_answer_count

  NUMBER_OF_ANSWERS = 4

  def validate_correct_answers
    correct_answers = self.answers.count {|answer| answer.correct == true }
    errors.add(:answers, "must have at #{correct_answers > 1 ? 'most':'least'} one correct answer") unless correct_answers == 1
  end

  def validate_answer_count
    errors.add(:answers, 'must have exactly four answers') unless self.answers.length == NUMBER_OF_ANSWERS
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :trivia_questions

  before_save :verify_score

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #Pagination limit per page
  self.per_page = 5

  private
  def verify_score
    self.score = 0 if self.score < 0
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!

  def check
    session[:streak_count] ||= 0

    @user_answer = Answer.find(params[:answer_id])
    #TODO switch update_attributes with incremnt and decrement
    if @user_answer.correct?
      current_user.update_attributes({score: current_user.score + 4})
      session[:streak_count] += 1
    else
      current_user.update_attributes({score: current_user.score - 1})
      update_streak_score #inherited from ApplicationController
    end
    redirect_to trivia_question_answer_path(@user_answer.trivia_question_id, @user_answer)
  end

  def show
    @user_answer = Answer.find(params[:id])
  end

  def destroy
    update_streak_score(delete_session = true)
    redirect_to root_path, notice: 'You have finished your game session!'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def sign_out(*args)
    update_streak_score(delete_session = true)
    super
  end

  def update_streak_score(delete_session = false)
    return unless current_user && session[:streak_count]
    current_user.update_attributes(streak: session[:streak_count]) if session[:streak_count] > current_user.streak
    delete_session ? session.delete(:streak_count) : session[:streak_count] = 0
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def ranking
    @users = User.page(params[:page]).order('score desc')
  end
end

app/controllers/trivia_questions_controller.rb
class TriviaQuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_trivia_question, only: [:show, :edit, :update, :destroy]


  # GET /trivia_questions
  # GET /trivia_questions.json
  def index
    @trivia_questions = TriviaQuestion.where(user_id: current_user.id)
  end

  # GET /trivia_questions/1
  # GET /trivia_questions/1.json
  def show
    @answers = @trivia_question.answers
  end

  # GET /trivia_questions/new
  def new
    @trivia_question = TriviaQuestion.new
    4.times do
      @trivia_question.answers.build
    end
  end

  # GET /trivia_questions/1/edit
  def edit
  end

  # POST /trivia_questions
  # POST /trivia_questions.json
  def create
    @trivia_question = TriviaQuestion.new(trivia_question_params)
    @trivia_question.user_id = current_user.id if current_user
    respond_to do |format|
      if @trivia_question.save
        format.html {redirect_to new_trivia_question_path, notice: 'Trivia question was successfully created. Add another one!'}
        format.json {render :show, status: :created, location: @trivia_question}
      else
        format.html {render :new}
        format.json {render json: @trivia_question.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /trivia_questions/1
  # PATCH/PUT /trivia_questions/1.json
  def update
    respond_to do |format|
      if @trivia_question.update(trivia_question_params)
        format.html {redirect_to @trivia_question, notice: 'Trivia question was successfully updated.'}
        format.json {render :show, status: :ok, location: @trivia_question}
      else
        format.html {render :edit}
        format.json {render json: @trivia_question.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /trivia_questions/1
  # DELETE /trivia_questions/1.json
  def destroy
    @trivia_question.destroy
    respond_to do |format|
      format.html {redirect_to trivia_questions_url, notice: 'Trivia question was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def play
    @trivia_question = TriviaQuestion.where.not(user_id: current_user.id).order("RANDOM()").first
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_trivia_question
    @trivia_question = TriviaQuestion.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def trivia_question_params
    params.require(:trivia_question).permit(:question, answers_attributes: Answer.attribute_names.map(&:to_sym).push(:_destroy))
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def render_flash
    flash_array = []
    flash.each do |type, messages|
      if messages.is_a?(String)
        flash_array << render(partial: 'shared/flash',
                              locals: { :type => type, :message => messages })
      else
        messages.each do |m|
          flash_array << render(partial: 'shared/flash',
                                locals: { :type => type, :message => m }) unless m.blank?
        end
      end
    end
    flash_array.join('').html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/trivia_questions_helper.rb
module TriviaQuestionsHelper
end

app/views/answers/show.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <% if @user_answer.correct %>
        <div class="panel panel-success">
    <% else %>
        <div class="panel panel-danger">
    <% end %>
          <div class="panel-heading">
          Question : <%= @user_answer.trivia_question.question%>
          </div>
          <div class="list-group">
            <li class="list-group-item">Your Answer: <%= @user_answer.answer_text %></li>
            <li class="list-group-item">Answer : <%= @user_answer.retrieve_answer.answer_text %></li>
          </div>
        </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <div class="well well-lg">
      <center>
      <h2>Current Score: <%= current_user.score %></h2>
        <h4>Highest Streak: <%= current_user.streak %></h4>
        <h5>Current Streak: <%= session[:streak_count] %></h5>
      </center>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <center>
      <div class="btn-group">
        <%= link_to "NEXT QUESTION", play_trivia_questions_path, class: 'btn btn-primary' %>
        <%= link_to "FINISH SESSION", trivia_question_answers_path, class: 'btn btn-danger', method: :delete %>
        <!--Update link-->
      </div>
    </center>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Trivia-App', root_path, class:'navbar-brand'%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Play', play_trivia_questions_path %></li>
        <li><%= link_to 'New Question', new_trivia_question_path %></li>
        <li><%= link_to 'Ranking', ranking_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><a>Score: <%= current_user.score %></a></li>
            <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShadowHealth</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <%= render_flash %>
        <%= render 'layouts/navbar' %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="col-sm-2 col-sm-offset-3">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Play</h3>
    </div>
    <div class="panel-body">
      <p>Ready to test your wits!</p>
      <%= link_to 'Play', play_trivia_questions_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

<div class="col-sm-2">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">Add A Question</h3>
    </div>
    <div class="panel-body">
      <p>Got a challenging question to ask?</p>
      <%= link_to 'New Question', new_trivia_question_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

<div class="col-sm-2">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3 class="panel-title">View Ranking</h3>
    </div>
    <div class="panel-body">
      <p>Curious where you stand?</p>
      <%= link_to 'Ranking', ranking_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/pages/ranking.html.erb
<div class="row">
  <div class="col-sm-10 col-sm-offset-1">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Email</th>
          <th>Score</th>
          <th>Highest Streak</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each.with_index(1) do |f, index| %>
          <tr>
            <td><%= @users.offset + index %></td>
            <td><%= f.email %></td>
            <td><%= f.score %></td>
            <td><%= f.streak %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= will_paginate @users %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="panel panel-danger" id="error_explanation">
      <div class="panel-heading">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <div classs="list-group">
        <% object.errors.full_messages.each do |msg| %>
            <li class="list-group-item"><%= msg %></li>
        <% end %>
      </div>
    </div>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
        <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
    <% end %>
<% end %>

app/views/trivia_questions/_answer_form.html.erb
<%= f.input :answer_text %>
<%= f.input :correct %>

app/views/trivia_questions/_form.html.erb
<div class="row">
  <div class="col-sm-4 col-sm-offset-2">
    <%= simple_form_for(@trivia_question) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="form-inputs">
          <%= f.input :question %>
        </div>

        <div class="fields">
          <%= f.simple_fields_for :answers do |builder| %>
            <%= render 'answer_form', f: builder %>
          <% end %>
        </div>

        <div class="form-actions">
          <%= f.button :submit %>
        </div>
    <% end %>
  </div>
</div>

app/views/trivia_questions/answer.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <% if @user_answer.correct %>
        <div class="panel panel-success">
    <% else %>
        <div class="panel panel-danger">
    <% end %>
          <div class="panel-heading">
          Question : <%= @user_answer.trivia_question.question%>
          </div>
          <div class="list-group">
            <li class="list-group-item">Your Answer: <%= @user_answer.answer_text %></li>
            <li class="list-group-item">Answer : <%= @user_answer.retrieve_answer.answer_text %></li>
          </div>
        </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <div class="well well-lg">
      <center>
      <h2>Current Score: <%= current_user.score %></h2>
      </center>
    </div>
  </div>
</div>

app/views/trivia_questions/edit.html.erb
<h1>Editing Trivia Question</h1>

<%= render 'form', trivia_question: @trivia_question %>

<%= link_to 'Show', @trivia_question %> |
<%= link_to 'Back', trivia_questions_path %>

app/views/trivia_questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trivia Questions</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trivia_questions.each do |trivia_question| %>
      <tr>
        <td><%= trivia_question.question %></td>
        <td><%= link_to 'Show', trivia_question %></td>
        <td><%= link_to 'Edit', edit_trivia_question_path(trivia_question) %></td>
        <td><%= link_to 'Destroy', trivia_question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trivia Question', new_trivia_question_path %>

app/views/trivia_questions/new.html.erb
<h1>New Trivia Question</h1>

<%= render 'form', trivia_question: @trivia_question %>

<%= link_to 'Back', trivia_questions_path %>

app/views/trivia_questions/play.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Question
      </div>
      <% if @trivia_question %>
      <%= content_tag :div, @trivia_question.question, class: 'panel-body' %>
    </div>

    <div class="list-group" id="item-button">
      <%= form_tag(check_trivia_question_answers_path(@trivia_question), method: :post) do |form|%>
        <% @trivia_question.answers.each do |f| %>
          <%= button_tag f.answer_text, class: 'list-group-item', name: 'answer_id', value: f.id.to_s %>
        <% end %>
      <% end %>
    </div>
      <% else %>
        <%= content_tag :div, 'Empty please wait for someone else to add a question!', class: 'panel-body' %>
    <% end %>
  </div>
</div>

app/views/trivia_questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @trivia_question.question %>
</p>

<% @answers.each do |f| %>
  <strong>Answers:</strong>
  <%= f.answer_text %>
  <%= f.correct %>
  <br>
<% end %>

<%= link_to 'Edit', edit_trivia_question_path(@trivia_question) %> |
<%= link_to 'Back', trivia_questions_path %>